<?php

/*
 * hook_node_presave
*/
function repo_node_presave($node) 
{
	// Trim the spaces in head and tail of title
	// Prevent url contains space after import to other sites
  if($node->type == "award") 
  {
		$node->title = trim($node->title);
  }
}

// hook_form_alter
function repo_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'student_profile_node_form') {
		unset($form['actions']['preview']); // No preview button
		$form['actions']['submit']['#value'] = 'Submit';	
	}
	else if($form_id == 'alumni_profile_node_form') {
		unset($form['actions']['preview']); // No preview button
    $form['actions']['submit']['#value'] = 'Submit';	
	}
}
